### ISSUE TITLE
renderer crash with blazor webassembly app (using the demo project as a base)

### ISSUE THREAD

**Issue by btarg** [TarekNajem04/Jenin.FontAwesome.Blazor#3]
```
fontawesome-Svg[nest]-config.js:1          Failed to load resource: the server responded with a status of 404 ()
fontawesome-config-utilities.js:1          Failed to load resource: the server responded with a status of 404 ()
all.min.css:1          Failed to load resource: the server responded with a status of 404 ()
blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
blazor.webassembly.js:1 blazor Loaded 9.61 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'removeChild')
      TypeError: Cannot read properties of null (reading 'removeChild')
          at H (https://localhost:7161/_framework/blazor.webassembly.js:1:17059)
          at H (https://localhost:7161/_framework/blazor.webassembly.js:1:17029)
          at H (https://localhost:7161/_framework/blazor.webassembly.js:1:17029)
          at se.applyEdits (https://localhost:7161/_framework/blazor.webassembly.js:1:21231)
          at se.updateComponent (https://localhost:7161/_framework/blazor.webassembly.js:1:20461)
          at https://localhost:7161/_framework/blazor.webassembly.js:1:57098
          at At.Fe._internal.renderBatch (https://localhost:7161/_framework/blazor.webassembly.js:1:57470)
          at Object.St [as invokeJSFromDotNet] (https://localhost:7161/_framework/blazor.webassembly.js:1:60156)
          at _mono_wasm_invoke_js_blazor (https://localhost:7161/_framework/dotnet.6.0.13.evxqgvpbeb.js:1:195300)
          at wasm://wasm/00971d3e:wasm-function[3308]:0xc6107
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'removeChild')
TypeError: Cannot read properties of null (reading 'removeChild')
    at H (https://localhost:7161/_framework/blazor.webassembly.js:1:17059)
    at H (https://localhost:7161/_framework/blazor.webassembly.js:1:17029)
    at H (https://localhost:7161/_framework/blazor.webassembly.js:1:17029)
    at se.applyEdits (https://localhost:7161/_framework/blazor.webassembly.js:1:21231)
    at se.updateComponent (https://localhost:7161/_framework/blazor.webassembly.js:1:20461)
    at https://localhost:7161/_framework/blazor.webassembly.js:1:57098
    at At.Fe._internal.renderBatch (https://localhost:7161/_framework/blazor.webassembly.js:1:57470)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7161/_framework/blazor.webassembly.js:1:60156)
    at _mono_wasm_invoke_js_blazor (https://localhost:7161/_framework/dotnet.6.0.13.evxqgvpbeb.js:1:195300)
    at wasm://wasm/00971d3e:wasm-function[3308]:0xc6107
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
window.Module.s.printErr @ blazor.webassembly.js:1
Fe._internal.dotNetCriticalError @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.13.evxqgvpbeb.js:1
$func219 @ 00971d3e:0x1a492
$func167 @ 00971d3e:0xce60
$func166 @ 00971d3e:0xbd73
$func2815 @ 00971d3e:0xabec4
$func1619 @ 00971d3e:0x6fc85
$func1617 @ 00971d3e:0x6fbf7
$func970 @ 00971d3e:0x50648
$func219 @ 00971d3e:0x1a44b
$func167 @ 00971d3e:0xce60
$func166 @ 00971d3e:0xbd73
$func2815 @ 00971d3e:0xabec4
$func1619 @ 00971d3e:0x6fc85
$func1623 @ 00971d3e:0x702f2
$mono_wasm_invoke_method @ 00971d3e:0x969f
Module._mono_wasm_invoke_method @ dotnet.6.0.13.evxqgvpbeb.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:19
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
ve @ blazor.webassembly.js:1
we @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
onGlobalEvent @ blazor.webassembly.js:1
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No element is currently associated with component 15
      Error: No element is currently associated with component 15
          at se.updateComponent (https://localhost:7161/_framework/blazor.webassembly.js:1:19948)
          at https://localhost:7161/_framework/blazor.webassembly.js:1:57098
          at At.Fe._internal.renderBatch (https://localhost:7161/_framework/blazor.webassembly.js:1:57470)
          at Object.St [as invokeJSFromDotNet] (https://localhost:7161/_framework/blazor.webassembly.js:1:60156)
          at _mono_wasm_invoke_js_blazor (https://localhost:7161/_framework/dotnet.6.0.13.evxqgvpbeb.js:1:195300)
          at wasm://wasm/00971d3e:wasm-function[3308]:0xc6107
          at wasm://wasm/00971d3e:wasm-function[167]:0xd5d3
          at wasm://wasm/00971d3e:wasm-function[166]:0xbd73
          at wasm://wasm/00971d3e:wasm-function[2815]:0xabec4
          at wasm://wasm/00971d3e:wasm-function[1619]:0x6fc85
Microsoft.JSInterop.JSException: No element is currently associated with component 15
Error: No element is currently associated with component 15
    at se.updateComponent (https://localhost:7161/_framework/blazor.webassembly.js:1:19948)
    at https://localhost:7161/_framework/blazor.webassembly.js:1:57098
    at At.Fe._internal.renderBatch (https://localhost:7161/_framework/blazor.webassembly.js:1:57470)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7161/_framework/blazor.webassembly.js:1:60156)
    at _mono_wasm_invoke_js_blazor (https://localhost:7161/_framework/dotnet.6.0.13.evxqgvpbeb.js:1:195300)
    at wasm://wasm/00971d3e:wasm-function[3308]:0xc6107
    at wasm://wasm/00971d3e:wasm-function[167]:0xd5d3
    at wasm://wasm/00971d3e:wasm-function[166]:0xbd73
    at wasm://wasm/00971d3e:wasm-function[2815]:0xabec4
    at wasm://wasm/00971d3e:wasm-function[1619]:0x6fc85
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
window.Module.s.printErr @ blazor.webassembly.js:1
Fe._internal.dotNetCriticalError @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.13.evxqgvpbeb.js:1
$func219 @ 00971d3e:0x1a492
$func167 @ 00971d3e:0xce60
$func166 @ 00971d3e:0xbd73
$func2815 @ 00971d3e:0xabec4
$func1619 @ 00971d3e:0x6fc85
$func1623 @ 00971d3e:0x702f2
$func3217 @ 00971d3e:0xc4e56
$mono_background_exec @ 00971d3e:0x9430f
Module._mono_background_exec @ dotnet.6.0.13.evxqgvpbeb.js:1
pump_message @ dotnet.6.0.13.evxqgvpbeb.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.13.evxqgvpbeb.js:1
$func2392 @ 00971d3e:0x942c0
$func3216 @ 00971d3e:0xc4de6
$func219 @ 00971d3e:0x1a4fa
$func167 @ 00971d3e:0xce60
$func166 @ 00971d3e:0xbd73
$func2815 @ 00971d3e:0xabec4
$func1619 @ 00971d3e:0x6fc85
$func1623 @ 00971d3e:0x702f2
$mono_wasm_invoke_method @ 00971d3e:0x969f
Module._mono_wasm_invoke_method @ dotnet.6.0.13.evxqgvpbeb.js:1
_call_method_with_converted_args @ dotnet.6.0.13.evxqgvpbeb.js:1
call_method @ dotnet.6.0.13.evxqgvpbeb.js:1
result @ dotnet.6.0.13.evxqgvpbeb.js:1
all.min.css:1          Failed to load resource: the server responded with a status of 404 ()
```

**Comment by TarekNajem04** [comment]
First I would like to thank you for this message, but the problem is that the files needed to run the program were not found.

| File| Description |
| --- | --- |
|fontawesome-Svg[nest]-config.js:1| **`Failed to load resource: the server responded with a status of 404 ()`**
| fontawesome-config-utilities.js:1| **`Failed to load resource: the server responded with a status of 404 ()`**
| all.min.css:1| **`Failed to load resource: the server responded with a status of 404 ()`**

Check all paths in the **index.html** file:
[**Solution Path**]\src\Jenin.FontAwesome.Blazor.Wasm.Sample\wwwroot\index.html
[Goto index.html](https://github.com/TarekNajem04/Jenin.FontAwesome.Blazor/blob/master/src/Jenin.FontAwesome.Blazor.Wasm.Sample/wwwroot/index.html)
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Jenin.FontAwesome.Blazor.Wasm.Sample</title>
    <base href="/" />

    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" />
    <!-- CSS only -->
    <link href="fontawesome/css/all.css" rel="stylesheet" />

    <link href="css/site.css" rel="stylesheet" />
    <link href="~/prism/prism.css" rel="stylesheet" />
    <link href="Jenin.FontAwesome.Blazor.Wasm.Sample.styles.css" rel="stylesheet" />

    <component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />

</head>

<body>
    <div id="app">Loading...</div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>

    <script src="js/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script src="bootstrap/js/bootstrap.bundle.js" type="text/javascript"></script>

    <script src="_content/Jenin.FontAwesome.Blazor/js/fontawesome-Svg[nest]-config.js" type="text/javascript"></script>
    <script src="fontawesome/js/all.min.js" type="text/javascript"></script>
    <script src="_content/Jenin.FontAwesome.Blazor/js/fontawesome-config-utilities.js" type="text/javascript"></script>

    <script>
        window.Prism = window.Prism || {};
        Prism.disableWorkerMessageHandler = true;
        Prism.manual = true;
    </script>
    <script src="~/prism/prism.js" type="text/javascript"></script>
    <script src="~/js/PrismUtilities.js" type="text/javascript"></script>
</body>

</html>
```
