### ISSUE TITLE
Animations crashes View

### ISSUE THREAD

**Issue by M0n7y5** [TarekNajem04/Jenin.FontAwesome.Blazor#4]
When i use for example spin animation and i call StateChanged then view will crash with this error.

```csharp
blazor.webview.js:1  An item with the same key has already been added. Key: --fa-animation-duration
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Jenin.FontAwesome.Blazor.Animations.Animation.AddStyles(Dictionary`2 styles)
   at Jenin.FontAwesome.Blazor.Components.Icon.AddStyles(Dictionary`2 styles)
   at Jenin.FontAwesome.Blazor.Components.ElementBase.BuildStyles()
   at Jenin.FontAwesome.Blazor.Components.ElementBase.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
```

**Comment by TarekNajem04** [comment]
I tried the scenario you talked about but no error occurred. Please provide a simple example to illustrate the error.

**Comment by TarekNajem04** [comment]
Thank you so much @M0n7y5 for taking the time to look into this.
We will close this issue. If this is still an issue for you, please provide us with more info with sample, and we will be able to respond to you as quickly as possible and investigate this further.
